export default {
    RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
    ADD_TO_CART: 'ADD_TO_CART',
    CHECKOUT_START: 'CHECKOUT_START',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILED: 'CHECKOUT_FAILED',
}
